# SPDX-FileCopyrightText: 2026 llmpalooza contributors
# SPDX-License-Identifier: Apache-2.0

# The digest of llmpalooza's own code in this module, for its implementations'
# identities (D-053; implementations.h). Run at build time by the custom
# command in CMakeLists.txt, which depends on every file it hashes, so an
# edit to any of them regenerates only the identity source.
#
#   cmake -DBASE=<module dir> -DNAMES=<a:b:...> -DOUTPUT=<file.cc> -P module_digest.cmake
#
# The digest is SHA-256 over one line per file, sorted by name:
# "<name> <SHA-256 of its bytes>\n". OUTPUT defines
# llmp::kernels::ggml::ModuleSourcesDigest(). Without OUTPUT, the script
# prints the digest instead (tests/unit/ggml_module_digest_test.cmake).

if(NOT BASE OR NOT NAMES)
  message(FATAL_ERROR "module_digest.cmake needs BASE and NAMES")
endif()
string(REPLACE ":" ";" names "${NAMES}")
list(SORT names)
set(lines "")
foreach(name IN LISTS names)
  if(NOT EXISTS "${BASE}/${name}" OR IS_DIRECTORY "${BASE}/${name}")
    message(FATAL_ERROR "module_digest.cmake: ${BASE}/${name} is not a file")
  endif()
  file(SHA256 "${BASE}/${name}" hash)
  string(APPEND lines "${name} ${hash}\n")
endforeach()
string(SHA256 digest "${lines}")

if(NOT OUTPUT)
  message(NOTICE "${digest}")
  return()
endif()
file(WRITE "${OUTPUT}.tmp"
  "// Generated by src/kernels/ggml/module_digest.cmake from the module's sources; do not edit.\n"
  "\n"
  "#include <string_view>\n"
  "\n"
  "#include \"kernels/ggml/implementations.h\"\n"
  "\n"
  "namespace llmp::kernels::ggml {\n"
  "\n"
  "std::string_view ModuleSourcesDigest() { return \"${digest}\"; }\n"
  "\n"
  "}  // namespace llmp::kernels::ggml\n")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
