# SPDX-FileCopyrightText: 2026 llmpalooza contributors
# SPDX-License-Identifier: Apache-2.0

# Derives the product version at build time (D-062) and records it where the
# build reports it: the generated source behind base/build_info.h, and the
# build receipt's `version` object. Every build runs it, so a commit or an
# edit since configure is never missed; either file is rewritten only when
# its contents change, so an unchanged version rebuilds nothing.
#
#   cmake -DSOURCE_DIR=<checkout> -DPROJECT_VERSION=<X.Y.Z> [-DGIT=<git>]
#         -DOUTPUT=<build_info.cc> -DRECEIPT=<llmp-receipt.json>
#         -DLICENSE_PROFILE=<profile> -DSDK=<identity> -DTARGET=<triple>
#         -P stamp.cmake
cmake_minimum_required(VERSION 4.4.3)

foreach(var IN ITEMS SOURCE_DIR PROJECT_VERSION OUTPUT RECEIPT LICENSE_PROFILE SDK TARGET)
  if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
    message(FATAL_ERROR "set ${var}")
  endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/derive.cmake")
llmp_version_derive(build SOURCE_DIR "${SOURCE_DIR}" PROJECT_VERSION "${PROJECT_VERSION}" GIT "${GIT}")

# Every value lands in a C++ string literal and a JSON string unescaped.
foreach(var IN ITEMS build_VERSION build_COMMIT LICENSE_PROFILE SDK TARGET)
  if(NOT "${${var}}" MATCHES "^[A-Za-z0-9._+-]*$")
    message(FATAL_ERROR "internal error: ${var} is `${${var}}`, which a build identity never holds")
  endif()
endforeach()
if(build_DIRTY)
  set(modified true)
else()
  set(modified false)
endif()

# Writes content to path only if it differs, so dependents rebuild only then.
function(write_if_changed path content)
  if(EXISTS "${path}")
    file(READ "${path}" current)
    if(current STREQUAL content)
      return()
    endif()
  endif()
  file(WRITE "${path}.tmp" "${content}")
  file(RENAME "${path}.tmp" "${path}")
endfunction()

string(JOIN "\n" source
  "// Generated by cmake/version/stamp.cmake on every build (D-062); do not edit."
  "#include \"base/build_info.h\""
  ""
  "namespace llmp::base {"
  ""
  "const BuildInfo& GetBuildInfo() {"
  "  static constexpr BuildInfo kBuildInfo{"
  "      .version = \"${build_VERSION}\","
  "      .commit = \"${build_COMMIT}\","
  "      .modified = ${modified},"
  "      .license_profile = \"${LICENSE_PROFILE}\","
  "      .sdk = \"${SDK}\","
  "      .target = \"${TARGET}\","
  "  };"
  "  return kBuildInfo;"
  "}"
  ""
  "}  // namespace llmp::base"
  "")
write_if_changed("${OUTPUT}" "${source}")

if(NOT EXISTS "${RECEIPT}")
  message(FATAL_ERROR "${RECEIPT} is missing; configure writes it (llmp_sources_finalize)")
endif()
file(READ "${RECEIPT}" receipt)
llmp_version_json(version build)
string(JSON recorded ERROR_VARIABLE error GET "${receipt}" version)
if(NOT error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "${RECEIPT} has no version: ${error}")
endif()
string(JSON same ERROR_VARIABLE error EQUAL "${recorded}" "${version}")
if(NOT same)
  string(JSON receipt SET "${receipt}" version "${version}")
  write_if_changed("${RECEIPT}" "${receipt}\n")
endif()
