# SPDX-FileCopyrightText: 2026 jitLLM contributors
# SPDX-License-Identifier: Apache-2.0

# Checks a build receipt against the source lock it names (D-057): the lock's
# digest and the SDK identity, the profile's closure (every core component
# plus those of the enabled modules, filtered by the CUDA setting), each component's tree
# against the lock, and that the receipt is official exactly when no
# component comes from a local override.
#
#   cmake -DRECEIPT=<jitllm-receipt.json> -DLOCK=<sources.lock.json>
#         -DSDK_IDENTITY=<identity> -P check_receipt.cmake
cmake_minimum_required(VERSION 4.4.3)

foreach(var IN ITEMS RECEIPT LOCK SDK_IDENTITY)
  if(NOT ${var})
    message(FATAL_ERROR "set ${var}")
  endif()
endforeach()
if(NOT EXISTS "${RECEIPT}")
  message(FATAL_ERROR "${RECEIPT} is missing; configure writes it (jitllm_sources_finalize)")
endif()
file(READ "${RECEIPT}" receipt)
file(READ "${LOCK}" lock)
file(SHA256 "${LOCK}" lock_sha256)

set(problems "")
function(get out json)
  string(JSON value ERROR_VARIABLE error GET "${json}" ${ARGN})
  if(NOT error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "${RECEIPT}: ${error}")
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

get(schema "${receipt}" schema)
get(recorded_lock "${receipt}" source_lock sha256)
get(sdk "${receipt}" sdk)
get(official "${receipt}" official)
string(JSON cuda_type TYPE "${receipt}" cuda)
if(NOT cuda_type STREQUAL "BOOLEAN")
  message(FATAL_ERROR "${RECEIPT}: cuda must be a boolean")
endif()
get(cuda "${receipt}" cuda)
string(JSON module_count LENGTH "${receipt}" modules)
set(modules "")
if(module_count GREATER 0)
  math(EXPR last "${module_count} - 1")
  foreach(i RANGE ${last})
    get(module "${receipt}" modules ${i})
    list(APPEND modules "${module}")
  endforeach()
endif()
if(NOT schema EQUAL 1)
  list(APPEND problems "schema is ${schema}, not 1")
endif()
if(NOT recorded_lock STREQUAL lock_sha256)
  list(APPEND problems "the receipt names lock ${recorded_lock}; ${LOCK} is ${lock_sha256}")
endif()
if(NOT sdk STREQUAL SDK_IDENTITY)
  list(APPEND problems "the receipt names SDK ${sdk}, not ${SDK_IDENTITY}")
endif()

# The closure the lock selects for the receipt's modules.
set(expected "")
string(JSON count LENGTH "${lock}" components)
math(EXPR last "${count} - 1")
foreach(i RANGE ${last})
  string(JSON id MEMBER "${lock}" components ${i})
  string(JSON tier GET "${lock}" components ${id} tier)
  string(JSON condition_type ERROR_VARIABLE condition_error TYPE "${lock}" components ${id} requires_cuda)
  if(NOT condition_error)
    if(NOT condition_type STREQUAL "BOOLEAN")
      message(FATAL_ERROR "${LOCK}: ${id}: requires_cuda must be a boolean")
    endif()
    get(requires_cuda "${lock}" components ${id} requires_cuda)
    if(requires_cuda AND NOT cuda)
      continue()
    endif()
  endif()
  if(tier STREQUAL "core")
    list(APPEND expected ${id})
  else()
    string(JSON module GET "${lock}" components ${id} module)
    if(module IN_LIST modules)
      list(APPEND expected ${id})
    endif()
  endif()
endforeach()

set(recorded "")
set(overridden FALSE)
string(JSON count LENGTH "${receipt}" components)
if(count GREATER 0)
  math(EXPR last "${count} - 1")
  foreach(i RANGE ${last})
    get(id "${receipt}" components ${i} id)
    get(locked "${receipt}" components ${i} locked_tree)
    get(actual "${receipt}" components ${i} source_tree)
    get(override "${receipt}" components ${i} override)
    get(modified "${receipt}" components ${i} modified)
    list(APPEND recorded ${id})
    string(JSON lock_tree ERROR_VARIABLE error GET "${lock}" components ${id} tree_sha256)
    if(NOT lock_tree STREQUAL locked)
      list(APPEND problems "${id}: the receipt's locked tree ${locked} is not the lock's ${lock_tree}")
    endif()
    if(override)
      set(overridden TRUE)
      if(actual STREQUAL locked)
        if(modified)
          list(APPEND problems "${id}: an override identical to the lock is marked modified")
        endif()
      else()
        if(NOT modified)
          list(APPEND problems "${id}: an override that differs from the lock is not marked modified")
        endif()
      endif()
    else()
      if(NOT actual STREQUAL locked)
        list(APPEND problems "${id}: built from tree ${actual}, not the locked ${locked}")
      endif()
      if(modified)
        list(APPEND problems "${id}: marked modified without an override")
      endif()
    endif()
  endforeach()
endif()
list(SORT expected)
list(SORT recorded)
if(NOT expected STREQUAL recorded)
  list(APPEND problems "the receipt's closure is [${recorded}]; the lock selects [${expected}]")
endif()
if(overridden)
  if(official)
    list(APPEND problems "a receipt with an overridden component is marked official")
  endif()
else()
  if(NOT official)
    list(APPEND problems "a receipt built only from locked sources is not marked official")
  endif()
endif()

if(problems)
  list(JOIN problems "\n  " text)
  message(FATAL_ERROR "${RECEIPT}:\n  ${text}")
endif()
message(STATUS "${RECEIPT}: closure [${recorded}], lock ${lock_sha256}, official ${official}")
